<a href="https://colab.research.google.com/github/aignepalencia/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3_Palencia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Assignment 3: Matrices 

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.


#Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


###Matrices



$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
       w -2x +3y +4z \\ 
      3w -x -3y +4z \\
      2w +4x +2y -4z\\
    \end{array}
\right. \\
$$

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 3 & -4 & 3 & -4\\ 1 & -1 & -5 & 1 \\ 3 & -1 & -4 & 2\end{bmatrix}\\
$$


###Declaring Matrices

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll keep on describing matrices, Let's make a function
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [ ]:
## Declaring a 2 x 2 Matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat (A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [2,3,4],
    [2,4,6]
])
describe_mat(G)


Matrix:
[[2 3 4]
 [2 4 6]]

Shape:	(2, 3)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [4, 8],
    [3, 9],
    [2, 6]
])
describe_mat(B)


Matrix:
[[4 8]
 [3 9]
 [2 6]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([7,7,7,8])
describe_mat(H)


Matrix:
[7 7 7 8]

Shape:	(4,)
Rank:	1



##Categorizing Matrices

###According to Shape

####Row and Column Matrices

In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    2, 4, 6, 8
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [3,6,-9, -12]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[2 4 6 8]

Shape:	(4,)
Rank:	1

Matrix:
[[  3   6  -9 -12]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix
col_mat = np.array([
    [4],
    [10],
    [7]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[ 4]
 [10]
 [ 7]]

Shape:	(3, 1)
Rank:	2



####Square Matrices

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [1,9,3],
    [9,4,6],
    [3,6,7]
])

non_square_mat = np.array([
    [5,4,3],
    [9,8,7]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[1 9 3]
 [9 4 6]
 [3 6 7]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[5 4 3]
 [9 8 7]]

Shape:	(2, 3)
Rank:	2
Is Square: False



##According to Element Values

###Null Matrix
 Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [ ]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


###Zero Matrix
A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((6,4))
zero_mat_sqr = np.zeros((3,6))
zero_mat_rct = np.zeros((9,8))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


###Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.




In [ ]:
ones_mat_row = np.ones((2,4))
ones_mat_sqr = np.ones((3,9))
ones_mat_rct = np.ones((5,8))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


###Diagonal Matrix
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.array([
    [2,4,6],
    [3,7,9],
    [4,8,1]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 4, 6],
       [3, 7, 9],
       [4, 8, 1]])

In [ ]:
d = np.diag([7,2,3,4])
d

array([[7, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

##Identity Matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.



In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##Upper Triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
    [1,2,3,4],
    [5,6,7,5],
    [9,2,-3,4],
    [5,6,7,-8]
])


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  5],
       [ 9,  2, -3,  4],
       [ 5,  6,  7, -8]])

In [ ]:
F = np.array([
              [2, 4, -6, -8, 10],
              [2, 4, -6, -8, 10],
              [2, 4, -6, -8, 10],
              [2, 4, -6, -8, 10],
              [2, 4, -6, -8, 10],
])
np.triu(F)

array([[ 2,  4, -6, -8, 10],
       [ 0,  4, -6, -8, 10],
       [ 0,  0, -6, -8, 10],
       [ 0,  0,  0, -8, 10],
       [ 0,  0,  0,  0, 10]])

##Lower Triangular Matrix
A lower triangular matrix is a matrix that has no values above the diagonal.



In [ ]:
np.array([
          [1, 9, 3],
          [2, 4, 6],
          [3, 7, 9],
])

array([[1, 9, 3],
       [2, 4, 6],
       [3, 7, 9]])

#Practice

1.Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown



In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

#Matrix Algebra

##Addition

In [ ]:
A= np.array([
             [1,2],
             [8,2],
             [9,2],
])
B= np. array ([
              [1,2],
              [1,2],
              [1,2],
])
A+B

array([[ 2,  4],
       [ 9,  4],
       [10,  4]])

##Subtraction

In [ ]:
A= np.array([
             [1,2],
             [9,2],
             [5,2],
])
B= np. array ([
              [1,2],
              [4,8],
              [1,2],
])
A-B

array([[ 0,  0],
       [ 5, -6],
       [ 4,  0]])

##Element-Wise Multiplication

In [ ]:
A= np.array([
             [1,7],
             [8,2],
             [1,9],
])
B= np. array ([
              [5,2],
              [1,2],
])
A@B

array([[12, 16],
       [42, 20],
       [14, 20]])

#Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.
Displays whether the matrix is square or non-square.
Displays whether the matrix is an empty matrix.
Displays if the matrix is an identity, ones, or zeros matrix
Use 5 sample matrices in which their shapes are not lower than(3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is a square matrix')
    else:
        print('The matrix is a non-square matrix')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is a ones matrix')
    else:
        print('The matrix is not a ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is a zeros matrix')
    else:
      print('The matrix is not a zeros matrix')

 


In [ ]:
print ('Matrix 1:')
RM1 = np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]])

mat_desc(RM1)


Matrix 1:
[[1 0 0]
 [5 3 0]
 [7 8 5]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is not a zeros matrix


In [ ]:
print ('Matrix 2:')
RM2 = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]])

mat_desc(RM2)

Matrix 2:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Shape: (3, 3)
Size: 9
Rank: 0
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is a zeros matrix


In [ ]:
print ('Matrix 3:')
RM3 = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]])

mat_desc(RM3)

Matrix 3:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (3, 3)
Size: 9
Rank: 1
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is a ones matrix
The matrix is not a zeros matrix


In [ ]:
print ('Matrix 4:')
RM4 = np.array([
    [7,12,3],
    [12,32,51],
    [32,51,13]])

mat_desc(RM4)

Matrix 4:
[[ 7 12  3]
 [12 32 51]
 [32 51 13]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is a square matrix
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is not a zeros matrix


#Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.
Returns the sum of the matrices.
Returns the differen of the matrices.
Returns the element-wise multiplication of the matrices.
Returns the element-wise division of the matrices.
Use 5 sample matrices in which their shapes are not lower than(3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [11]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The shape of both matrices are not the same. Could not perform operations.')
        return
    print('Sum of the given matrices:')
    msum = mat1 + mat2
    print(msum)
    print('Difference of the given matrices:')
    mdiff = mat1 - mat2
    print(mdiff)
    print('Element-wise multiplication of the matrices:')
    mmul = np.multiply(mat1, mat2)
    print(mmul)
    print('Element-wise division of the matrices:')
    mmul = np.divide(mat1, mat2)
    print(mmul)

In [16]:
print('Sample Case: 1')
mat_operations([[7, 12, 3], [12, 32, 51], [32, 51, 13]], [[7, 12, 3], [12, 3, 5], [2, 1, 1]])
print('Sample Case: 2')
mat_operations([[7, 2, 3], [2, 2, 1], [2, 1, 3]], [[8, 2, 7], [2, 3, 5], [2 , 1, 1]])
print('Sample Case: 3')
mat_operations([[7, 2, 3], [12, 2, 1], [3, 1, 13]], [[7, 1, 2, 3], [1, 2, 3, 5], [0, 7, 3, 5], [2, 1, 1, 4]])
print('Sample Case: 4')
mat_operations([[0, 0, 0], [2, 0, 1], [0, 1, 3]], [[1, 0, 0], [2, 3, 5], [0, 0, 1]])
print('Sample Case: 5')
mat_operations([[7, 1, 2, 3], [1, 2, 3, 5], [0, 7, 3, 5]], [[7, 2, 3], [12, 2, 1], [3, 1, 13]])

Sample Case: 1
Matrix 1: [[ 7 12  3]
 [12 32 51]
 [32 51 13]]
Matrix 2: [[ 7 12  3]
 [12  3  5]
 [ 2  1  1]]
Sum of the given matrices:
[[14 24  6]
 [24 35 56]
 [34 52 14]]
Difference of the given matrices:
[[ 0  0  0]
 [ 0 29 46]
 [30 50 12]]
Element-wise multiplication of the matrices:
[[ 49 144   9]
 [144  96 255]
 [ 64  51  13]]
Element-wise division of the matrices:
[[ 1.          1.          1.        ]
 [ 1.         10.66666667 10.2       ]
 [16.         51.         13.        ]]
Sample Case: 2
Matrix 1: [[7 2 3]
 [2 2 1]
 [2 1 3]]
Matrix 2: [[8 2 7]
 [2 3 5]
 [2 1 1]]
Sum of the given matrices:
[[15  4 10]
 [ 4  5  6]
 [ 4  2  4]]
Difference of the given matrices:
[[-1  0 -4]
 [ 0 -1 -4]
 [ 0  0  2]]
Element-wise multiplication of the matrices:
[[56  4 21]
 [ 4  6  5]
 [ 4  1  3]]
Element-wise division of the matrices:
[[0.875      1.         0.42857143]
 [1.         0.66666667 0.2       ]
 [1.         1.         3.        ]]
Sample Case: 3
Matrix 1: [[ 7  2  3]
 [12  2  1]
 [ 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


#Conclusion