<a href="https://colab.research.google.com/github/aignepalencia/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_4_Palencia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CpE
## Laboratory 7 : Matrix Operations

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

In [ ]:
A = np.array([
    [1 ,0, 5],
    [5, -16, 9],
    [0, -3, 13]
])
A

array([[  1,   0,   5],
       [  5, -16,   9],
       [  0,  -3,  13]])

In [ ]:
AT1 = np.transpose(A)

In [ ]:
AT2 = A.T

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [1,-2,13,14],
    [11,9,2,10],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

## Dot Product / Inner Product
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. 

In [ ]:
X = np.array([
    [9,6],
    [0,7]
])
Y = np.array([
    [-9,0],
    [12,9]
])

In [ ]:
np.dot(X,Y)

array([[-9, 54],
       [84, 63]])

In [ ]:
X.dot(Y)

array([[-9, 54],
       [84, 63]])

In [ ]:
X @ Y

array([[-9, 54],
       [84, 63]])

In [ ]:
np.matmul(X,Y)

array([[-9, 54],
       [84, 63]])

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

In [ ]:
A = np.array([
    [9, -4],
    [15, -2],
    [0, 5]
])
B = np.array([
    [10,19],
    [13,-3],
    [-14,-2]
])
C = np.array([
    [9,11,9],
    [1,9,-2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
A @ C

array([[ 77,  63,  89],
       [133, 147, 139],
       [  5,  45, -10]])

In [ ]:
B @ C

array([[ 109,  281,   52],
       [ 114,  116,  123],
       [-128, -172, -122]])

In [ ]:
A @ B.T

array([[  14,  129, -118],
       [ 112,  201, -206],
       [  95,  -15,  -10]])

In [ ]:
X = np.array([
    [1,12,9,10]
])
Y = np.array([
    [12,7,14,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 12, 144, 108, 120],
       [  7,  84,  63,  70],
       [ 14, 168, 126, 140],
       [ -1, -12,  -9, -10]])

### Rule 2: Dot Product has special properties

In [ ]:
A = np.array([
    [3,22,1],
    [14,5,11],
    [1,1,0]
])
B = np.array([
    [4,10,6],
    [14,1,9],
    [1,-4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant
A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. 

In [ ]:
A = np.array([
    [1,8],
    [10,3]
])
np.linalg.det(A)

-77.00000000000001

In [ ]:
B = np.array([
    [1,13,15,6],
    [9,3,10,3],
    [3,16,8,2],
    [5,12,6,3]
])
np.linalg.det(B)

2669.000000000002

## Inverse
The inverse of a matrix is another fundamental operation in matrix algebra.Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

In [ ]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,10,9,4,3],
    [1,6,4,4,8,43,11],
    [8,6,8,7,1,6,11],
    [-5,15,2,10,10,16,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])