<a href="https://colab.research.google.com/github/aignepalencia/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Lab_Report_3_Multiplication_Properties_of_Matrices_Palencia_Roxas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Activity, Task 1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
A = np.array([
    [6,6,6],
    [1,2,3],
    [5,5,5]
])
B = np.array([
    [11,12,13],
    [16,15,14],
    [23,22,21]
])
C = np.array([
    [55,66,77],
    [67,23,25],
    [62,10,90]
])

#First Property


In [ ]:
AmultiB = A @ B
AmultiB

array([[300, 294, 288],
       [112, 108, 104],
       [250, 245, 240]])

In [ ]:
BmultiA = B @ A
BmultiA

array([[143, 155, 167],
       [181, 196, 211],
       [265, 287, 309]])

In [ ]:
np.array_equal(AmultiB,BmultiA)

False

#Second Property

In [ ]:
BmultiC = B @ C
BmultiC

array([[2215, 1132, 2317],
       [2753, 1541, 2867],
       [4041, 2234, 4211]])

In [ ]:
Left = A @ BmultiC
Left

array([[54054, 29442, 56370],
       [19844, 10916, 20684],
       [45045, 24535, 46975]])

In [ ]:
Right = AmultiB @ C
Right

array([[54054, 29442, 56370],
       [19844, 10916, 20684],
       [45045, 24535, 46975]])

In [ ]:
np.array_equal(Left,Right)

True

#Third Property


In [ ]:
BplusC = B + C
BplusC

array([[ 66,  78,  90],
       [ 83,  38,  39],
       [ 85,  32, 111]])

In [ ]:
AmultiC = A @ C
AmultiC

array([[1104,  594, 1152],
       [ 375,  142,  397],
       [ 920,  495,  960]])

In [ ]:
AmultiBlusC= A @ BplusC
AmultiBlusC

array([[1404,  888, 1440],
       [ 487,  250,  501],
       [1170,  740, 1200]])

In [ ]:
AmultiBplusAmultiC = AmultiB + AmultiC
AmultiBplusAmultiC

array([[1404,  888, 1440],
       [ 487,  250,  501],
       [1170,  740, 1200]])

In [ ]:
np.array_equal(AmultiBlusC,AmultiBplusAmultiC)

True

#Fourth Property

In [ ]:
Left4th = BplusC @ A
Left4th

array([[ 924, 1002, 1080],
       [ 731,  769,  807],
       [1097, 1129, 1161]])

In [ ]:
Right4th = (B @ A) + (C @ A)
Right4th

array([[ 924, 1002, 1080],
       [ 731,  769,  807],
       [1097, 1129, 1161]])

In [ ]:
np.array_equal(Left4th,Right4th)

True

#Fifth Property

In [ ]:
identmat = np.identity(3)
identmat


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Proof5th = A @ identmat
Proof5th

array([[6., 6., 6.],
       [1., 2., 3.],
       [5., 5., 5.]])

In [ ]:
np.array_equal(A,Proof5th)

True

#Sixth Property

In [ ]:
Zeromat = np.zeros((3,3))
Zeromat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Proof6th = A @ Zeromat
Proof6th

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(Zeromat,Proof6th)

True